export const ROUTES = {
  AUTH: "/",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  VERIFY_EMAIL: "/verify-email",
  SOCIAL: "/app/social",
  SOCIAL_STREAMS: "/app/social/streams",
  SOCIAL_CHAT_MESSAGES: "/app/social/chat/messages",
  SOCIAL_PEOPLE: "/app/social/people",
  SOCIAL_CONNECTIONS: "/app/social/connections",
  SOCIAL_PHOTOS: "/app/social/photos",
  SOCIAL_VIDEOS: "/app/social/videos",
  SOCIAL_NOTIFICATIONS: "/app/social/notifications",
  SOCIAL_PROFILE: "/app/social/profile/:username/:userId",
  SOCIAL_SETTINGS: "/app/social/settings",
  SOCIAL_SEARCH: "/app/social/search",
}
