export const ROUTES = {
  AUTH: "/",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  SOCIAL: "/app/social",
  SOCIAL_STREAMS: "/app/social/streams",
  SOCIAL_CHAT_MESSAGES: "/app/social/chat/messages",
  SOCIAL_PEOPLE: "/app/social/people",
  SOCIAL_FOLLOWERS: "/app/social/followers",
  SOCIAL_FOLLOWING: "/app/social/following",
  SOCIAL_PHOTOS: "/app/social/photos",
  SOCIAL_VIDEOS: "/app/social/videos",
  SOCIAL_NOTIFICATIONS: "/app/social/notifications",
  SOCIAL_PROFILE: "/app/social/profile/:username",
}
